# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1c2c1e1b62b3278ad5d69c9c89822d2634b0d53c2b8540df69f53deec36bd6f5dd1f683b12aa4cd7340420d6655c16b20dff44228c88640de06517e73853123

test:
  secret_key_base: 0e3a4180230c84a4ee5a8023aea3a4f8800c5cc0aae0adfedb166dec8323bd6611616f0fb4be001b4a27b600c5de0fa9e7255f2bba2d5d2245783e9bc3f1eb0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
